// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package algorithm

import (
	"demo/api/algorithm"
)

type ControllerV1 struct{}

func NewV1() algorithm.IAlgorithmV1 {
	return &ControllerV1{}
}
