
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "sqlite::@file(./data/sqlite.db)"
        descriptionTag: true

# 数据库配置  
database:
  default:
    link: "sqlite::@file(./data/sqlite.db)"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app