// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// algorithmDao is the data access object for the table algorithm.
// You can define custom methods on it to extend its functionality as needed.
type algorithmDao struct {
	*internal.AlgorithmDao
}

var (
	// Algorithm is a globally accessible object for table algorithm operations.
	Algorithm = algorithmDao{internal.NewAlgorithmDao()}
)

// Add your custom methods and functionality below.
