// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// mqttMessageDao is the data access object for the table mqtt_message.
// You can define custom methods on it to extend its functionality as needed.
type mqttMessageDao struct {
	*internal.MqttMessageDao
}

var (
	// MqttMessage is a globally accessible object for table mqtt_message operations.
	MqttMessage = mqttMessageDao{internal.NewMqttMessageDao()}
)

// Add your custom methods and functionality below.
